import './globals.css'
import { Inter } from 'next/font/google'
import { Sigmar } from 'next/font/google'

const inter = Inter({ 
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-inter'
})

const sigmar = Sigmar({
  weight: '400',
  subsets: ['latin'],
  variable:'--font-sigmar',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${sigmar.className} `}>{children}</body>
    </html>
  )
}
