import './globals.css'
import { Inter, Roboto_Mono } from 'next/font/google'

const roboro = Roboto_Mono({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable:'--font-roboto',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${roboro.className}  `}>{children}</body>
    </html>
  )
}
