import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
} from 'react-icons/ai'
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';

export default function Home() {
  return (
    <div  >
      <Head>
        <title>Abdulkareem Tukur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10' >
        <section className='min-h-screen' >
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>developedbyabdulkareem</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a href="#"
                className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-1 ml-8 rounded-md '
                >Resume</a>
                </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-4xl text-teal-600 font-medium'>
              Abdulkareem Tukur
            </h2>
            <h3 className='text-2xl py-2' >Developer and designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!</p>
          </div>
          <div className='text-4xl gap-16 text-gray-800 py-2 flex justify-center'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
          </div>
          <div>
            <Image src={deved} layout='fill'/>
          </div>
        </section>
      </main>

    </div>
  )
}
