import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillMail,
  AiFillGithub,
} from 'react-icons/ai'
import { useState } from 'react';
import Image from 'next/image';
import code from "../public/code.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {

  const [darkMode, setDarkMode] = useState(true)

  return (
    <div className={ darkMode ? 'dark' : ''} >

      <Head>
        <title>Abdulkareem Tukur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyabdulkareem</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => { setDarkMode(!darkMode) }}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Abdul Kareem 
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
            React Frontend Web Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            I develope web applications using React and other modern technologies. I am a computer science student and I am passionate for creating intuitive and user-friendly web experiences.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle href='' className=' cursor-pointer '/>
              <AiFillGithub className=' cursor-pointer '/>
              <AiFillLinkedin className=' cursor-pointer '/>
              <AiFillMail className=' cursor-pointer '/>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Skills</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              <span className="text-teal-500"> Strong understanding </span>
              of HTML, CSS, JavaScript and React
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              <span className="text-teal-500"> Proficient </span>
              in using Git for version control, Figma, Redux, GraphQL, and Apollo
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              <span className="text-teal-500"> Experience </span>
              with responsive web design and mobile-first development
            </p>
          </div>
          <div className="pt-20">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image className='mx-auto' src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
              Are you ready to take your online presence to the next level and create a website that truly represents your brand or business?
              If you have an idea for your next great website, I'd love to help make it a reality. Together, we can turn your vision into a functional,
              visually appealing, and user-friendly website that will attract and retain visitors. Let's start turning your dream website into a reality.
              </p>
            </div>
          </div>
        </section>

        <section>
          <h3 className="text-5xl py-5 pt-20 text-center text-teal-600 font-medium dark:text-teal-400 ">
              Projects
          </h3>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/4 flex-1'>
              <Image src={web1} className='hover:bg-teal-800 bg-opacity-5 rounded-lg object-cover' width={'100%'} height={'100%'}  />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'}  />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'}  />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'}  />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'}  />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'}  />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
